version: '3'
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CHROME_DRIVER_URL: "http://chrome:4444"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tangocho
      - /tangocho/log
      - /tangocho/tmp
      - vendor_bundle:/tangocho/vendor/bundle
      - node_modules:/tangocho/node_modules
      - storage:/tangocho/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - '4444:4444'
    shm_size: 128m
