FROM ruby:3.0.3-alpine3.13

WORKDIR /tangocho
COPY Gemfile* /tangocho/
RUN apk update && apk add --no-cache -t .build-dependencies \
  alpine-sdk \
  build-base \
  mysql-client \
  && apk add --no-cache \
  bash \
  mysql-dev \
  nodejs \
  tzdata \
  yarn \
  && gem install bundler \
  && bundle install \
  && apk add --no-cache libc6-compat \
  && ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 \
  && apk del --purge .build-dependencies \
  && rm -rf /usr/local/bundle/cache/* /usr/local/share/.cache/* /var/cache/* /tmp/*

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
