version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: web
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      REDIS_URL: "redis://redis:6379"
      CHROME_DRIVER_URL: "http://chrome:4444"
    depends_on:
      - db
      - redis
      - chrome
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
    shm_size: 128m
